apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-workloads.yaml
  - background-workloads.yaml
  - event-workloads.yaml
  - availability.yaml
  - autoscaling.yaml
  - ingress.yaml
