apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../foundation
  - dependencies.yaml
  - runtime-secrets.yaml

patches:
  - path: runtime-config.patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: platform-runtime-config
      namespace: fastapi-platform
